name: Tests
on:
  pull_request:
    branches: 
      - main
      - master

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v1
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v4
      with:
        node-version: '16.x'
    - name: Install
      run: pnpm install
    - name: Linting
      run: pnpm lint:js
    - name: Test
      run: pnpm run test --coverage

  integration_tests:
    name: Integration Tests
    strategy:
      matrix:
        ember_version: ['3.10', '3.13']
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v1
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v4
      with:
        node-version: '16.x'
    - name: Install
      run: pnpm install
    - name: Test
      env:
        EMBER_VERSION: ${{ matrix.ember_version }}
      run: pnpm run test:integration
